# Copyright 2022 Aurora Operations, Inc.

site_name: "The Au units library"
site_description: "A C++ units library, by Aurora"
site_url: https://aurora-opensource.github.io/au
site_author: "Au team"
copyright: Copyright &copy; 2022, Aurora Innovation, Inc. All rights reserved

repo_url: https://github.com/aurora-opensource/au
edit_uri: blob/main/docs

theme:
  name: material
  favicon: assets/favicon.ico
  logo: assets/au-logo.png

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

extra_css:
  - tweaks.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true

  - markdown.extensions.smarty
  - attr_list
  - admonition
  - footnotes
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
