# Copyright 2022 Aurora Operations, Inc.

agents:
  queue: "ci-tiny"

steps:
  - label: "Clang 11"
    command: bazel test --config=clang11 //...:all
  - label: "Clang 14"
    command: bazel test --config=clang14 //...:all
