# Copyright 2026 Aurora Operations, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Minimal legacy WORKSPACE project to test that Au can be consumed via
# http_archive or local_repository. This simulates a user's project that
# depends on Au using the traditional WORKSPACE approach.

workspace(name = "workspace_test_client")

local_repository(
    name = "au",
    path = "..",
)
