# Copyright 2022 Aurora Operations, Inc.

name: check-license-headers

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@dc323e67f16fb5f7663d20ff7941f27f5809e9b6 #v2.6.0
      - uses: viperproject/check-license-header@971caaf7d1641bb2c6a49acd06b018a5ce51ad6e # v1.0.5
        with:
          path: .
          config: .github/license-check/license-config.json
          strict: true
