name: clang-format-lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.14
      with:
        source: './au'
        extensions: 'hh,cc'
        clangFormatVersion: 14.0.0
        style: file
