# Copyright 2022 Aurora Operations, Inc.

name: deploy-doc-site

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@dc323e67f16fb5f7663d20ff7941f27f5809e9b6 #v2.6.0
      - name: Update remote gh-pages history
        run: git fetch origin gh-pages:gh-pages
      - name: Build and deploy
        run: bazel run //:update_docs -- gh-deploy
